language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
before_install:
  - export NODE_ENV=test
  - export TEST_DB_USERNAME=postgres
  - export TEST_DB_PASSWORD=null
  - export TEST_DB_NAME=postit_test
  - export CODECLIMATE_REPO_TOKEN=b95782ae5d24665d875eca8e39db4206a35ac1ec33c4e57c660c6956cbe443e7
services:
  - postgresql
before_script:
  - psql -c 'CREATE DATABASE postit_test;' -U postgres
  - sh server/scripts/build.sh
  - "npm run start &"
after_success:
  - npm run coveralls
  - codeclimate-test-reporter < coverage/lcov.info
