language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
before_install:
  - sh sever/scripts/build.sh
services:
  - postgresql
before_script:
  - psql -c 'CREATE DATABASE postit_test;' -U postgres
  - "npm run start &"
after_success:
  - npm run coveralls
  - codeclimate-test-reporter < coverage/lcov.info
