export default {
  MESSAGE_POSTED: 'MESSAGE_POSTED',
  USER_ADDED: 'USER_ADDED',
  USER_REMOVED: 'USER_REMOVED',
  GROUP_DELETED: 'GROUP_DELETED',
  GROUP_UPDATED: 'GROUP_UPDATED',
  USER_LEFT: 'USER_LEFT'
}